### ISSUE TITLE
The first level of Auto Obtainum/ Auto Offerings is supposed to be non-refundable, is anyway.

### ISSUE THREAD

**Issue by Kappaclystic** [Pseudo-Corp/SynergismOfficial#28]
![Screenshot (7)](https://cdn.discordapp.com/attachments/730669616870981674/808168713769058325/Screenshot_7.png)
![Screenshot (8)](https://user-images.githubusercontent.com/63431093/107170605-d1bc8e80-698e-11eb-8046-2195fe45701d.png)
![Screenshot (9)](https://user-images.githubusercontent.com/63431093/107170612-d41ee880-698e-11eb-8568-fc0581ece4a0.png)

**Comment by Kappaclystic** [comment]
Also, the C10 requirement reducer doesn't refund correctly.

**Comment by Pseudonian** [comment]
This was fixed in 634096d (though I'm sorry for the incorrect issue# displayed)

- Added attribute "Minimum refund level" for respective shop upgrades
- Updated description of shop tomes to be non-refundable as this is intended (some weird bugs happened in the past when this was refundable

Thank you for reporting this bug!
